#sdfasfsadf
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mldemo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch: #配置路径匹配策略
      matching-strategy: ant_path_matcher #使用ant风格
  web:
    googleexcute: explorer #本地浏览器地址
    loginurl: http://localhost:${server.port}/swagger-ui/index.html #要打开的网址
    isopenurl: false #是否要启动时打开浏览器

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #配置打印sql日志
  global-config:
    db-config:
      id-type: auto #主键自增
      logic-delete-value: 1 #逻辑删除值
      logic-not-delete-value: 0 #逻辑未删除值
  mapper-locations: classpath:mapper/*.xml
  logging:
    level:
      com:
        example:
          demo:
            mapper=debug:

swagger: #配置swagger
  enabled: true #是否开启swagger